sudo: required
services:
  - docker

before_install:
  - docker build -t czachman/docker-react -f Dockerfile.dev .

script:
  - docker run czachman/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment_name: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-279274087707"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
